apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    app: nginx-okd
  name: nginx-okd
spec:
  replicas: 1
  selector:
    app: nginx-okd
    deploymentconfig: nginx-okd
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      labels:
        app: nginx-okd
        deploymentconfig: nginx-okd
    spec:
      containers:
      - image: lvarin/nginx-okd:latest
        imagePullPolicy: Always
        name: nginx-okd
        volumeMounts:
        - mountPath: /var/log/nginx
          name: logs
        ports:
        - containerPort: 80
          protocol: TCP
        - containerPort: 8081
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 500Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      - image: lvarin/filebeat-okd:latest
#        imagePullPolicy: Always
        name: filebeat
        volumeMounts:
        - mountPath: /var/log/nginx
          name: logs
        - mountPath: /usr/share/filebeat/filebeat.yml
          subPath: filebeat.yml
          name: filebeat-sidecar-config
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 500Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      volumes:
      - name: logs
        emptyDir: {}
      - name: filebeat-sidecar-config
        configMap:
          defaultMode: 420
          items:
          - key: filebeat.yml
            path: filebeat.yml
          name: filebeat-sidecar-config
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  test: false
status: {}
