apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx-okd
  name: nginx-okd
spec:
  ports:
  - name: 8081-tcp
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: nginx-okd
    deploymentconfig: nginx-okd
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
